FROM node:lts AS build_stage
RUN mkdir -p /application/
WORKDIR /application
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=build_stage /application/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]