const ActionTypes = {
    GET_USER_DATA: 'GET_USER_DATA',
    GET_PROFILE: 'GET_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',

    GET_ARTICLES: 'GET_ARTICLES',

    GET_ALL_AVAILABLE_CRYPTOS: 'GET_ALL_AVAILABLE_CRYPTOS',
    ENABLE_CRYPTO: 'ENABLE_CRYPTO',
    DISABLE_CRYPTO: 'DISABLE_CRYPTO',
    GET_REGISTERED_CRYPTOS: 'GET_REGISTERED_CRYPTOS',
    GET_CRYPTO_BY_CODE: 'GET_CRYPTO_BY_CODE',
    GET_CRYPTO_HISTORY_BY_CODE: 'GET_CRYPTO_HISTORY_BY_CODE',

    UPDATE_CURRENCY: 'UPDATE_CURRENCY',
    UPDATE_SELECTED_CRYPTO: 'UPDATE_SELECTED_CRYPTO',
};

export default ActionTypes;
